package com.hundsun.ta.datacenter.daointerface;

import com.hundsun.ta.datacenter.dataobject.ETFFundInfoDO;
import com.hundsun.ta.datacenter.dataobject.FundCodeDO;

import java.util.List;

public interface ETFFundInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TFUNDINFO
     *
     * @mbggenerated
     */
    int insert(ETFFundInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TFUNDINFO
     *
     * @mbggenerated
     */
    int insertSelective(ETFFundInfoDO record);

    /**
     * 获取etf所有基金列表
     * @return
     */
    List<FundCodeDO> getAllFundCode();
}