package com.hundsun.ta.datacenter.daointerface;

import com.hundsun.ta.datacenter.dataobject.NavSplitFundDO;

import java.util.List;

public interface NavSplitFundDOMapper {
    /**
     * 选择全部数据
     * @return
     */
    List<NavSplitFundDO> selectAllData();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAV_SPLIT_FUND
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * 插入数据
     * @mbggenerated
     */
    int insert(NavSplitFundDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAV_SPLIT_FUND
     *
     * @mbggenerated
     */
    int insertSelective(NavSplitFundDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAV_SPLIT_FUND
     *
     * @mbggenerated
     */
    NavSplitFundDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAV_SPLIT_FUND
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NavSplitFundDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table NAV_SPLIT_FUND
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NavSplitFundDO record);

}