package com.hundsun.ta.datacenter.daointerface;

import com.hundsun.ta.datacenter.dataobject.FundCodeDO;
import com.hundsun.ta.datacenter.dataobject.RttaFundInfoDO;

import java.util.List;

public interface RttaFundInfoDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TFUNDINFO
     *
     * @mbggenerated
     */
    int insert(RttaFundInfoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TFUNDINFO
     *
     * @mbggenerated
     */
    int insertSelective(RttaFundInfoDO record);

    /**
     * 获取实时TA基金类列表
     * @return
     */
    List<FundCodeDO> getAllFundCode();
}