package com.hundsun.ta.datacenter.daointerface;

import com.hundsun.ta.datacenter.dataobject.RttaSaleStatDO;

public interface RttaSaleStatDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSALESTAT
     *
     * @mbggenerated
     */
    int insert(RttaSaleStatDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSALESTAT
     *
     * @mbggenerated
     */
    int insertSelective(RttaSaleStatDO record);
}