package com.hundsun.ta.datacenter.daointerface;

import com.hundsun.ta.datacenter.dataobject.TA4SaleStatDO;

public interface TA4SaleStatDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSALESTAT
     *
     * @mbggenerated
     */
    int insert(TA4SaleStatDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TSALESTAT
     *
     * @mbggenerated
     */
    int insertSelective(TA4SaleStatDO record);
}