package com.hundsun.ta.datacenter.dataobject;

import java.util.Date;

public class NavSplitFundDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAV_SPLIT_FUND.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAV_SPLIT_FUND.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAV_SPLIT_FUND.gmt_modified
     *
     * @mbggenerated
     */
    private Date gmtModified;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAV_SPLIT_FUND.fund_code
     *
     * @mbggenerated
     */
    private String fundCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAV_SPLIT_FUND.sub_fund_code
     *
     * @mbggenerated
     */
    private String subFundCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAV_SPLIT_FUND.split_type
     *
     * @mbggenerated
     */
    private String splitType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column NAV_SPLIT_FUND.is_yoga
     *
     * @mbggenerated
     */
    private String isYoga;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAV_SPLIT_FUND.id
     *
     * @return the value of NAV_SPLIT_FUND.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAV_SPLIT_FUND.id
     *
     * @param id the value for NAV_SPLIT_FUND.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAV_SPLIT_FUND.gmt_create
     *
     * @return the value of NAV_SPLIT_FUND.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAV_SPLIT_FUND.gmt_create
     *
     * @param gmtCreate the value for NAV_SPLIT_FUND.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAV_SPLIT_FUND.gmt_modified
     *
     * @return the value of NAV_SPLIT_FUND.gmt_modified
     *
     * @mbggenerated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAV_SPLIT_FUND.gmt_modified
     *
     * @param gmtModified the value for NAV_SPLIT_FUND.gmt_modified
     *
     * @mbggenerated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAV_SPLIT_FUND.fund_code
     *
     * @return the value of NAV_SPLIT_FUND.fund_code
     *
     * @mbggenerated
     */
    public String getFundCode() {
        return fundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAV_SPLIT_FUND.fund_code
     *
     * @param fundCode the value for NAV_SPLIT_FUND.fund_code
     *
     * @mbggenerated
     */
    public void setFundCode(String fundCode) {
        this.fundCode = fundCode == null ? null : fundCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAV_SPLIT_FUND.sub_fund_code
     *
     * @return the value of NAV_SPLIT_FUND.sub_fund_code
     *
     * @mbggenerated
     */
    public String getSubFundCode() {
        return subFundCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAV_SPLIT_FUND.sub_fund_code
     *
     * @param subFundCode the value for NAV_SPLIT_FUND.sub_fund_code
     *
     * @mbggenerated
     */
    public void setSubFundCode(String subFundCode) {
        this.subFundCode = subFundCode == null ? null : subFundCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAV_SPLIT_FUND.split_type
     *
     * @return the value of NAV_SPLIT_FUND.split_type
     *
     * @mbggenerated
     */
    public String getSplitType() {
        return splitType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAV_SPLIT_FUND.split_type
     *
     * @param splitType the value for NAV_SPLIT_FUND.split_type
     *
     * @mbggenerated
     */
    public void setSplitType(String splitType) {
        this.splitType = splitType == null ? null : splitType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column NAV_SPLIT_FUND.is_yoga
     *
     * @return the value of NAV_SPLIT_FUND.is_yoga
     *
     * @mbggenerated
     */
    public String getIsYoga() {
        return isYoga;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column NAV_SPLIT_FUND.is_yoga
     *
     * @param isYoga the value for NAV_SPLIT_FUND.is_yoga
     *
     * @mbggenerated
     */
    public void setIsYoga(String isYoga) {
        this.isYoga = isYoga == null ? null : isYoga.trim();
    }
}