package com.hundsun.ta.datacenter.dataobject;

import java.math.BigDecimal;

public class RttaFundInfoDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TFUNDINFO.VC_FUNDCODE
     *
     * @mbggenerated
     */
    private String vcFundcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TFUNDINFO.VC_FUNDNAME
     *
     * @mbggenerated
     */
    private String vcFundname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TFUNDINFO.C_SHARETYPE
     *
     * @mbggenerated
     */
    private String cSharetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TFUNDINFO.C_MONEYTYPE
     *
     * @mbggenerated
     */
    private String cMoneytype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TFUNDINFO.VC_TACODE
     *
     * @mbggenerated
     */
    private String vcTacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TFUNDINFO.C_STATE
     *
     * @mbggenerated
     */
    private String cState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TFUNDINFO.C_TYPE
     *
     * @mbggenerated
     */
    private String cType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TFUNDINFO.EN_MANAGERATIO
     *
     * @mbggenerated
     */
    private BigDecimal enManageratio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TFUNDINFO.EN_MANAGERFEE
     *
     * @mbggenerated
     */
    private BigDecimal enManagerfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TFUNDINFO.EN_SERVICERATE
     *
     * @mbggenerated
     */
    private BigDecimal enServicerate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TFUNDINFO.EN_LASTSHARES
     *
     * @mbggenerated
     */
    private BigDecimal enLastshares;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TFUNDINFO.VC_GRADEFUND
     *
     * @mbggenerated
     */
    private String vcGradefund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TFUNDINFO.C_CARRYMODE
     *
     * @mbggenerated
     */
    private String cCarrymode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TFUNDINFO.C_SUPPORTDAYSHARE
     *
     * @mbggenerated
     */
    private String cSupportdayshare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TFUNDINFO.VC_MGRCODE
     *
     * @mbggenerated
     */
    private String vcMgrcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TFUNDINFO.VC_TRUSTEECODE
     *
     * @mbggenerated
     */
    private String vcTrusteecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TFUNDINFO.VC_GZCODE
     *
     * @mbggenerated
     */
    private String vcGzcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TFUNDINFO.C_SENDLIQDATA
     *
     * @mbggenerated
     */
    private String cSendliqdata;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TFUNDINFO.C_EXPSALESERVICEFARE
     *
     * @mbggenerated
     */
    private String cExpsaleservicefare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TFUNDINFO.EN_REALSHARES_PRE
     *
     * @mbggenerated
     */
    private BigDecimal enRealsharesPre;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFUNDINFO.VC_FUNDCODE
     *
     * @return the value of TFUNDINFO.VC_FUNDCODE
     *
     * @mbggenerated
     */
    public String getVcFundcode() {
        return vcFundcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFUNDINFO.VC_FUNDCODE
     *
     * @param vcFundcode the value for TFUNDINFO.VC_FUNDCODE
     *
     * @mbggenerated
     */
    public void setVcFundcode(String vcFundcode) {
        this.vcFundcode = vcFundcode == null ? null : vcFundcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFUNDINFO.VC_FUNDNAME
     *
     * @return the value of TFUNDINFO.VC_FUNDNAME
     *
     * @mbggenerated
     */
    public String getVcFundname() {
        return vcFundname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFUNDINFO.VC_FUNDNAME
     *
     * @param vcFundname the value for TFUNDINFO.VC_FUNDNAME
     *
     * @mbggenerated
     */
    public void setVcFundname(String vcFundname) {
        this.vcFundname = vcFundname == null ? null : vcFundname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFUNDINFO.C_SHARETYPE
     *
     * @return the value of TFUNDINFO.C_SHARETYPE
     *
     * @mbggenerated
     */
    public String getcSharetype() {
        return cSharetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFUNDINFO.C_SHARETYPE
     *
     * @param cSharetype the value for TFUNDINFO.C_SHARETYPE
     *
     * @mbggenerated
     */
    public void setcSharetype(String cSharetype) {
        this.cSharetype = cSharetype == null ? null : cSharetype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFUNDINFO.C_MONEYTYPE
     *
     * @return the value of TFUNDINFO.C_MONEYTYPE
     *
     * @mbggenerated
     */
    public String getcMoneytype() {
        return cMoneytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFUNDINFO.C_MONEYTYPE
     *
     * @param cMoneytype the value for TFUNDINFO.C_MONEYTYPE
     *
     * @mbggenerated
     */
    public void setcMoneytype(String cMoneytype) {
        this.cMoneytype = cMoneytype == null ? null : cMoneytype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFUNDINFO.VC_TACODE
     *
     * @return the value of TFUNDINFO.VC_TACODE
     *
     * @mbggenerated
     */
    public String getVcTacode() {
        return vcTacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFUNDINFO.VC_TACODE
     *
     * @param vcTacode the value for TFUNDINFO.VC_TACODE
     *
     * @mbggenerated
     */
    public void setVcTacode(String vcTacode) {
        this.vcTacode = vcTacode == null ? null : vcTacode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFUNDINFO.C_STATE
     *
     * @return the value of TFUNDINFO.C_STATE
     *
     * @mbggenerated
     */
    public String getcState() {
        return cState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFUNDINFO.C_STATE
     *
     * @param cState the value for TFUNDINFO.C_STATE
     *
     * @mbggenerated
     */
    public void setcState(String cState) {
        this.cState = cState == null ? null : cState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFUNDINFO.C_TYPE
     *
     * @return the value of TFUNDINFO.C_TYPE
     *
     * @mbggenerated
     */
    public String getcType() {
        return cType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFUNDINFO.C_TYPE
     *
     * @param cType the value for TFUNDINFO.C_TYPE
     *
     * @mbggenerated
     */
    public void setcType(String cType) {
        this.cType = cType == null ? null : cType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFUNDINFO.EN_MANAGERATIO
     *
     * @return the value of TFUNDINFO.EN_MANAGERATIO
     *
     * @mbggenerated
     */
    public BigDecimal getEnManageratio() {
        return enManageratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFUNDINFO.EN_MANAGERATIO
     *
     * @param enManageratio the value for TFUNDINFO.EN_MANAGERATIO
     *
     * @mbggenerated
     */
    public void setEnManageratio(BigDecimal enManageratio) {
        this.enManageratio = enManageratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFUNDINFO.EN_MANAGERFEE
     *
     * @return the value of TFUNDINFO.EN_MANAGERFEE
     *
     * @mbggenerated
     */
    public BigDecimal getEnManagerfee() {
        return enManagerfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFUNDINFO.EN_MANAGERFEE
     *
     * @param enManagerfee the value for TFUNDINFO.EN_MANAGERFEE
     *
     * @mbggenerated
     */
    public void setEnManagerfee(BigDecimal enManagerfee) {
        this.enManagerfee = enManagerfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFUNDINFO.EN_SERVICERATE
     *
     * @return the value of TFUNDINFO.EN_SERVICERATE
     *
     * @mbggenerated
     */
    public BigDecimal getEnServicerate() {
        return enServicerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFUNDINFO.EN_SERVICERATE
     *
     * @param enServicerate the value for TFUNDINFO.EN_SERVICERATE
     *
     * @mbggenerated
     */
    public void setEnServicerate(BigDecimal enServicerate) {
        this.enServicerate = enServicerate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFUNDINFO.EN_LASTSHARES
     *
     * @return the value of TFUNDINFO.EN_LASTSHARES
     *
     * @mbggenerated
     */
    public BigDecimal getEnLastshares() {
        return enLastshares;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFUNDINFO.EN_LASTSHARES
     *
     * @param enLastshares the value for TFUNDINFO.EN_LASTSHARES
     *
     * @mbggenerated
     */
    public void setEnLastshares(BigDecimal enLastshares) {
        this.enLastshares = enLastshares;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFUNDINFO.VC_GRADEFUND
     *
     * @return the value of TFUNDINFO.VC_GRADEFUND
     *
     * @mbggenerated
     */
    public String getVcGradefund() {
        return vcGradefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFUNDINFO.VC_GRADEFUND
     *
     * @param vcGradefund the value for TFUNDINFO.VC_GRADEFUND
     *
     * @mbggenerated
     */
    public void setVcGradefund(String vcGradefund) {
        this.vcGradefund = vcGradefund == null ? null : vcGradefund.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFUNDINFO.C_CARRYMODE
     *
     * @return the value of TFUNDINFO.C_CARRYMODE
     *
     * @mbggenerated
     */
    public String getcCarrymode() {
        return cCarrymode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFUNDINFO.C_CARRYMODE
     *
     * @param cCarrymode the value for TFUNDINFO.C_CARRYMODE
     *
     * @mbggenerated
     */
    public void setcCarrymode(String cCarrymode) {
        this.cCarrymode = cCarrymode == null ? null : cCarrymode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFUNDINFO.C_SUPPORTDAYSHARE
     *
     * @return the value of TFUNDINFO.C_SUPPORTDAYSHARE
     *
     * @mbggenerated
     */
    public String getcSupportdayshare() {
        return cSupportdayshare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFUNDINFO.C_SUPPORTDAYSHARE
     *
     * @param cSupportdayshare the value for TFUNDINFO.C_SUPPORTDAYSHARE
     *
     * @mbggenerated
     */
    public void setcSupportdayshare(String cSupportdayshare) {
        this.cSupportdayshare = cSupportdayshare == null ? null : cSupportdayshare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFUNDINFO.VC_MGRCODE
     *
     * @return the value of TFUNDINFO.VC_MGRCODE
     *
     * @mbggenerated
     */
    public String getVcMgrcode() {
        return vcMgrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFUNDINFO.VC_MGRCODE
     *
     * @param vcMgrcode the value for TFUNDINFO.VC_MGRCODE
     *
     * @mbggenerated
     */
    public void setVcMgrcode(String vcMgrcode) {
        this.vcMgrcode = vcMgrcode == null ? null : vcMgrcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFUNDINFO.VC_TRUSTEECODE
     *
     * @return the value of TFUNDINFO.VC_TRUSTEECODE
     *
     * @mbggenerated
     */
    public String getVcTrusteecode() {
        return vcTrusteecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFUNDINFO.VC_TRUSTEECODE
     *
     * @param vcTrusteecode the value for TFUNDINFO.VC_TRUSTEECODE
     *
     * @mbggenerated
     */
    public void setVcTrusteecode(String vcTrusteecode) {
        this.vcTrusteecode = vcTrusteecode == null ? null : vcTrusteecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFUNDINFO.VC_GZCODE
     *
     * @return the value of TFUNDINFO.VC_GZCODE
     *
     * @mbggenerated
     */
    public String getVcGzcode() {
        return vcGzcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFUNDINFO.VC_GZCODE
     *
     * @param vcGzcode the value for TFUNDINFO.VC_GZCODE
     *
     * @mbggenerated
     */
    public void setVcGzcode(String vcGzcode) {
        this.vcGzcode = vcGzcode == null ? null : vcGzcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFUNDINFO.C_SENDLIQDATA
     *
     * @return the value of TFUNDINFO.C_SENDLIQDATA
     *
     * @mbggenerated
     */
    public String getcSendliqdata() {
        return cSendliqdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFUNDINFO.C_SENDLIQDATA
     *
     * @param cSendliqdata the value for TFUNDINFO.C_SENDLIQDATA
     *
     * @mbggenerated
     */
    public void setcSendliqdata(String cSendliqdata) {
        this.cSendliqdata = cSendliqdata == null ? null : cSendliqdata.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFUNDINFO.C_EXPSALESERVICEFARE
     *
     * @return the value of TFUNDINFO.C_EXPSALESERVICEFARE
     *
     * @mbggenerated
     */
    public String getcExpsaleservicefare() {
        return cExpsaleservicefare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFUNDINFO.C_EXPSALESERVICEFARE
     *
     * @param cExpsaleservicefare the value for TFUNDINFO.C_EXPSALESERVICEFARE
     *
     * @mbggenerated
     */
    public void setcExpsaleservicefare(String cExpsaleservicefare) {
        this.cExpsaleservicefare = cExpsaleservicefare == null ? null : cExpsaleservicefare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TFUNDINFO.EN_REALSHARES_PRE
     *
     * @return the value of TFUNDINFO.EN_REALSHARES_PRE
     *
     * @mbggenerated
     */
    public BigDecimal getEnRealsharesPre() {
        return enRealsharesPre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TFUNDINFO.EN_REALSHARES_PRE
     *
     * @param enRealsharesPre the value for TFUNDINFO.EN_REALSHARES_PRE
     *
     * @mbggenerated
     */
    public void setEnRealsharesPre(BigDecimal enRealsharesPre) {
        this.enRealsharesPre = enRealsharesPre;
    }
}