package com.hundsun.ta.datacenter.dataobject;

import java.math.BigDecimal;

public class RttaSaleStatDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSALESTAT.D_CDATE
     *
     * @mbggenerated
     */
    private String dCdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSALESTAT.D_HOLDDATE
     *
     * @mbggenerated
     */
    private String dHolddate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSALESTAT.VC_FUNDCODE
     *
     * @mbggenerated
     */
    private String vcFundcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSALESTAT.VC_AGENCYNO
     *
     * @mbggenerated
     */
    private String vcAgencyno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSALESTAT.VC_PARTNERID
     *
     * @mbggenerated
     */
    private String vcPartnerid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSALESTAT.EN_SHARE
     *
     * @mbggenerated
     */
    private BigDecimal enShare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSALESTAT.EN_BALANCE
     *
     * @mbggenerated
     */
    private BigDecimal enBalance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSALESTAT.EN_HOLDRATIO
     *
     * @mbggenerated
     */
    private BigDecimal enHoldratio;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSALESTAT.EN_MANAGERFEE
     *
     * @mbggenerated
     */
    private BigDecimal enManagerfee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSALESTAT.EN_SERVICEFARE
     *
     * @mbggenerated
     */
    private BigDecimal enServicefare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSALESTAT.EN_INCOME
     *
     * @mbggenerated
     */
    private BigDecimal enIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSALESTAT.EN_REALSHARES_PRE
     *
     * @mbggenerated
     */
    private BigDecimal enRealsharesPre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSALESTAT.EN_TAILFARE
     *
     * @mbggenerated
     */
    private BigDecimal enTailfare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TSALESTAT.EN_LASTWORSHARE
     *
     * @mbggenerated
     */
    private BigDecimal enLastworshare;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSALESTAT.D_CDATE
     *
     * @return the value of TSALESTAT.D_CDATE
     *
     * @mbggenerated
     */
    public String getdCdate() {
        return dCdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSALESTAT.D_CDATE
     *
     * @param dCdate the value for TSALESTAT.D_CDATE
     *
     * @mbggenerated
     */
    public void setdCdate(String dCdate) {
        this.dCdate = dCdate == null ? null : dCdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSALESTAT.D_HOLDDATE
     *
     * @return the value of TSALESTAT.D_HOLDDATE
     *
     * @mbggenerated
     */
    public String getdHolddate() {
        return dHolddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSALESTAT.D_HOLDDATE
     *
     * @param dHolddate the value for TSALESTAT.D_HOLDDATE
     *
     * @mbggenerated
     */
    public void setdHolddate(String dHolddate) {
        this.dHolddate = dHolddate == null ? null : dHolddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSALESTAT.VC_FUNDCODE
     *
     * @return the value of TSALESTAT.VC_FUNDCODE
     *
     * @mbggenerated
     */
    public String getVcFundcode() {
        return vcFundcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSALESTAT.VC_FUNDCODE
     *
     * @param vcFundcode the value for TSALESTAT.VC_FUNDCODE
     *
     * @mbggenerated
     */
    public void setVcFundcode(String vcFundcode) {
        this.vcFundcode = vcFundcode == null ? null : vcFundcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSALESTAT.VC_AGENCYNO
     *
     * @return the value of TSALESTAT.VC_AGENCYNO
     *
     * @mbggenerated
     */
    public String getVcAgencyno() {
        return vcAgencyno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSALESTAT.VC_AGENCYNO
     *
     * @param vcAgencyno the value for TSALESTAT.VC_AGENCYNO
     *
     * @mbggenerated
     */
    public void setVcAgencyno(String vcAgencyno) {
        this.vcAgencyno = vcAgencyno == null ? null : vcAgencyno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSALESTAT.VC_PARTNERID
     *
     * @return the value of TSALESTAT.VC_PARTNERID
     *
     * @mbggenerated
     */
    public String getVcPartnerid() {
        return vcPartnerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSALESTAT.VC_PARTNERID
     *
     * @param vcPartnerid the value for TSALESTAT.VC_PARTNERID
     *
     * @mbggenerated
     */
    public void setVcPartnerid(String vcPartnerid) {
        this.vcPartnerid = vcPartnerid == null ? null : vcPartnerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSALESTAT.EN_SHARE
     *
     * @return the value of TSALESTAT.EN_SHARE
     *
     * @mbggenerated
     */
    public BigDecimal getEnShare() {
        return enShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSALESTAT.EN_SHARE
     *
     * @param enShare the value for TSALESTAT.EN_SHARE
     *
     * @mbggenerated
     */
    public void setEnShare(BigDecimal enShare) {
        this.enShare = enShare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSALESTAT.EN_BALANCE
     *
     * @return the value of TSALESTAT.EN_BALANCE
     *
     * @mbggenerated
     */
    public BigDecimal getEnBalance() {
        return enBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSALESTAT.EN_BALANCE
     *
     * @param enBalance the value for TSALESTAT.EN_BALANCE
     *
     * @mbggenerated
     */
    public void setEnBalance(BigDecimal enBalance) {
        this.enBalance = enBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSALESTAT.EN_HOLDRATIO
     *
     * @return the value of TSALESTAT.EN_HOLDRATIO
     *
     * @mbggenerated
     */
    public BigDecimal getEnHoldratio() {
        return enHoldratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSALESTAT.EN_HOLDRATIO
     *
     * @param enHoldratio the value for TSALESTAT.EN_HOLDRATIO
     *
     * @mbggenerated
     */
    public void setEnHoldratio(BigDecimal enHoldratio) {
        this.enHoldratio = enHoldratio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSALESTAT.EN_MANAGERFEE
     *
     * @return the value of TSALESTAT.EN_MANAGERFEE
     *
     * @mbggenerated
     */
    public BigDecimal getEnManagerfee() {
        return enManagerfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSALESTAT.EN_MANAGERFEE
     *
     * @param enManagerfee the value for TSALESTAT.EN_MANAGERFEE
     *
     * @mbggenerated
     */
    public void setEnManagerfee(BigDecimal enManagerfee) {
        this.enManagerfee = enManagerfee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSALESTAT.EN_SERVICEFARE
     *
     * @return the value of TSALESTAT.EN_SERVICEFARE
     *
     * @mbggenerated
     */
    public BigDecimal getEnServicefare() {
        return enServicefare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSALESTAT.EN_SERVICEFARE
     *
     * @param enServicefare the value for TSALESTAT.EN_SERVICEFARE
     *
     * @mbggenerated
     */
    public void setEnServicefare(BigDecimal enServicefare) {
        this.enServicefare = enServicefare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSALESTAT.EN_INCOME
     *
     * @return the value of TSALESTAT.EN_INCOME
     *
     * @mbggenerated
     */
    public BigDecimal getEnIncome() {
        return enIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSALESTAT.EN_INCOME
     *
     * @param enIncome the value for TSALESTAT.EN_INCOME
     *
     * @mbggenerated
     */
    public void setEnIncome(BigDecimal enIncome) {
        this.enIncome = enIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSALESTAT.EN_REALSHARES_PRE
     *
     * @return the value of TSALESTAT.EN_REALSHARES_PRE
     *
     * @mbggenerated
     */
    public BigDecimal getEnRealsharesPre() {
        return enRealsharesPre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSALESTAT.EN_REALSHARES_PRE
     *
     * @param enRealsharesPre the value for TSALESTAT.EN_REALSHARES_PRE
     *
     * @mbggenerated
     */
    public void setEnRealsharesPre(BigDecimal enRealsharesPre) {
        this.enRealsharesPre = enRealsharesPre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSALESTAT.EN_TAILFARE
     *
     * @return the value of TSALESTAT.EN_TAILFARE
     *
     * @mbggenerated
     */
    public BigDecimal getEnTailfare() {
        return enTailfare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSALESTAT.EN_TAILFARE
     *
     * @param enTailfare the value for TSALESTAT.EN_TAILFARE
     *
     * @mbggenerated
     */
    public void setEnTailfare(BigDecimal enTailfare) {
        this.enTailfare = enTailfare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TSALESTAT.EN_LASTWORSHARE
     *
     * @return the value of TSALESTAT.EN_LASTWORSHARE
     *
     * @mbggenerated
     */
    public BigDecimal getEnLastworshare() {
        return enLastworshare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TSALESTAT.EN_LASTWORSHARE
     *
     * @param enLastworshare the value for TSALESTAT.EN_LASTWORSHARE
     *
     * @mbggenerated
     */
    public void setEnLastworshare(BigDecimal enLastworshare) {
        this.enLastworshare = enLastworshare;
    }
}